# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
